### ISSUE TITLE
linkage_wrap TypeError: argument 2 must be numpy.ndarray, not numpy.ndarray

### ISSUE THREAD

**Issue by adriennefranke** [dmuellner/fastcluster#11]
I'm working with the [Dedupe](https://github.com/dedupeio/dedupe) library and I'm making a standard Deduper with it. I get the the point in the Dedupe example to do the clustering (deduper.match) and it blocks records just fine, but then I get this Traceback that goes all the way to the linkage_wrap function from this fastcluster package and the error is quite confusing! "argument 2 must be numpy.ndarray, not numpy.ndarray" Any help would be appreciated. I've searched through all the issues here and also on Dedupe, and have come up empty handed. Here is the Traceback:

TypeError                                 Traceback (most recent call last)
<ipython-input-48-321fa927f670> in <module>
     40 
     41 print('clustering...')
---> 42 clustered_dupes = deduper.match(data_dict, threshold)
     43 print('# duplicate sets', len(clustered_dupes))

~/.conda/envs/dev/lib/python3.7/site-packages/dedupe/api.py in match(self, data, threshold, generator)
    221             return clusters
    222         else:
--> 223             return list(clusters)
    224 
    225     def threshold(self, data, recall_weight=1.5):  # pragma: no cover

~/.conda/envs/dev/lib/python3.7/site-packages/dedupe/api.py in matchBlocks(self, blocks, threshold, *args, **kwargs)
    123         logger.debug("matching done, begin clustering")
    124 
--> 125         for cluster in self._cluster(matches, threshold, *args, **kwargs):
    126             yield cluster
    127 

~/.conda/envs/dev/lib/python3.7/site-packages/dedupe/clustering.py in cluster(dupes, threshold, max_components)
    153             linkage = fastcluster.linkage(condensed_distances,
    154                                           method='centroid',
--> 155                                           preserve_input=True)
    156 
    157             partition = hcluster.fcluster(linkage,

~/.conda/envs/dev/lib/python3.7/site-packages/fastcluster.py in linkage(X, method, metric, preserve_input)
    245     Z = empty((N-1,4))
    246     if N > 1:
--> 247         linkage_wrap(N, X, Z, mthidx[method])
    248     return Z
    249 

TypeError: argument 2 must be numpy.ndarray, not numpy.ndarray

**Comment by dmuellner** [comment]
This is indeed a confusing error message. Could you create a minimal example that I ran run myself and reproduce the issue?

**Comment by adriennefranke** [comment]
I'm not sure what I did, but this strange error went away and I couldn't get it to show up again. So I'll close this for now. Thanks for the response!
