### ISSUE TITLE
interpretation of output

### ISSUE THREAD

**Issue by rotoscan** [dmuellner/fastcluster#12]
Dear Daniel,

thank you for this tool.

I would like to ask some assistance on how to intrepret the output if this clustering method. I will supply an example code:

```
import fastcluster
import os
import sys


obj_distances = {
    ('obj2', 'obj3'): 1.8,
    ('obj3', 'obj1'): 1.95,
    ('obj1', 'obj4'): 2.5,
    ('obj1', 'obj2'): 2.0,
    ('obj4', 'obj2'): 2.1,
    ('obj3', 'obj4'): 1.58,
}

matrix=obj_distances

keys = [sorted(k) for k in matrix.keys()]
values = matrix.values()
sorted_keys, distances = zip(*sorted(zip(keys, values)))

cluster=fastcluster.linkage(distances, method='average')

print cluster
print type(cluster)
print len(cluster)
```

And when I run:
```
[[2.   3.   1.58 2.  ]
 [1.   4.   1.95 3.  ]
 [0.   5.   2.15 4.  ]]
<type 'numpy.ndarray'>
3
```
You see, I need to have the information of which objects (obj1, obj2, etc) clustered so I can proceed with my work. But I don't quite understand the output if the tool. Could you please help me out with that briefly?

I would deeply appreciate. Thank you.

Kind Regards
Rodolfo

**Comment by dmuellner** [comment]
The output is the same as in scipy.cluster.hierarchy.linkage. It is documented here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html.
