### ISSUE TITLE
Installing fastcluster without numpy first installed

### ISSUE THREAD

**Issue by ahill187** [dmuellner/fastcluster#15]
If you try to install `fastcluster` in an environment without `numpy` first installed, you get the error :
```ModuleNotFoundError: No module named 'numpy'```

I can see that this is because the `setup.py` file imports `numpy` at the top of the file. It is listed as a dependency, but after it has been imported?

**Comment by dmuellner** [comment]
Python needs NumPy header files to compile the fastcluster C++ library. Accordingly, there is
```
include_dirs=[numpy.get_include()]
```
in setup.py.
