### ISSUE TITLE
[R] Support user defined metric in `hclust.vector`

### ISSUE THREAD

**Issue by talegari** [dmuellner/fastcluster#16]
Thanks for this wonderful package!

`hclust.vector` does not seem to support user-defined function for metric like python version's `linkage_vector`.

This will be a game changer to obtain fast hclust on vector data without precomputing the dist object.
 
PS: I am trying to code hdbscan on the lines of the excellent python [hdbscan](https://github.com/scikit-learn-contrib/hdbscan) in R

**Comment by dmuellner** [comment]
Not every distance function is suitable for the vector algorithm but the distance matrix approach works with any distance function.

**Comment by talegari** [comment]
I agree with the fact that "distance matrix approach works with any distance function".

Storing distances becomes prohibitive after a point as its O(n^2). Hence, the request is to provide the user-defined function argument to R's interface via `hclust.vector`.

Here is the example code for python version from the docs:

```
fn = lambda u, v:  numpy.sqrt(((u-v)*(u-v)).sum())
linkage_vector(X, method='single', metric=fn)
```

**Comment by dmuellner** [comment]
Your example is covered by
```
linkage_vector(X, method='single', metric='eucidlean')
```
Do you have a particular metric in mind that you want to cover in addition to the already implemented ones?

**Comment by TaoSunVoyage** [comment]
Hi @dmuellner, I was wondering if it's possible to cover string distance metrics.

When doing string clustering, we have to first calculate the distance matrix (using the package `stringdist`) and then use `hclust`.

**Comment by talegari** [comment]
In R version, if `metric` argument (of `hclust.vector`) can accept a UDF(user defined function) like the python version, one can work with a lot of custom distance metrics.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/10041819/117649877-aaec3f00-b1ad-11eb-96be-547a8655907c.png">

**Comment by dmuellner** [comment]
Unfortunately, I don't have time nowadays to implement this myself. Feel free to send a pull request if you manage to add the functionality to the R interface.
