### ISSUE TITLE
fastcluster 1.2.4 is not installable on python 3.10 with newest version of pip (using default args)

### ISSUE THREAD

**Issue by fgregg** [dmuellner/fastcluster#30]
with python 3.10, and pip 22, fastcluster is not installable with a normal pip command

the reason is that the pyproject.toml file for 1.2.4 looks like this

```
[build-system]
# We specify older version of numpy for the build environment because
# numpy tries to maintain backwards compatibility but not forward
# compatibility. So, if a user tries to use an extension that was compiled
# along with an earlier version of numpy (say 1.12) than the user has on
# their current system, that will work (say 1.15). However, if the
# extension was compiled with a numpy 1.15 and the user has 1.12 on their
# system, the extension will not work.
#
# For each version of Python, we choose the earliest versions of numpy that
# has binary wheels for that Python version for window, mac, and linux.
# Otherwise building fastcluster would require compiling numpy which
# would make things much, much slower.
requires = ["setuptools",
            "wheel",
            "numpy==1.10.4; python_version<'3.6'",
            "numpy==1.12.1; python_version=='3.6'",
            "numpy==1.15.0; python_version=='3.7'",
            "numpy==1.17.3; python_version=='3.8'",
            "numpy==1.19.3; python_version=='3.9'"]
```

notice there is no fallback for numpy for python_version greater than 3.9. that means that numpy *is* not installed, and so it can't build.

this is already fixed in the code in this repo: https://github.com/dmuellner/fastcluster/blob/master/pyproject.toml

@dmuellner would you consider cutting a new release.

you don't have to bring in #29 before doing this.

**Comment by tschm** [comment]
@gautier-marti @tschm

**Comment by dmuellner** [comment]
Unfortunately, Travis builds are failing since I merged the change to pyproject.toml. See https://app.travis-ci.com/github/dmuellner/fastcluster/builds. Please let me know if you have a clue what is wrong and how to resolve it.

**Comment by fgregg** [comment]
i'll take a look

**Comment by fgregg** [comment]
the failing build on travis are not related to the updated pyproject.toml file.

the issue is that scipy no longer provided wheels in the manylinux1 format but only in newer manylinux formats.

this means that for the manylinux1 builds on travis, it is trying to build scipy from source and is failing due to missing system dependencies.

this is the kind of thing that cibuildwheel should help with a lot!

would you like me make a pr to update the manylinux1 builds on travis so they will pass again?

**Comment by dmuellner** [comment]
Thanks for the investigation, Forest! It seems that SciPy does not have any 32-bit wheel build at all for Python 3.10. (I looked at the file list at https://pypi.org/project/scipy/#files.)

Do you need 32-bit fastcluster wheels for your projects, or would it be OK to drop 32-bit wheel support?

**Comment by dmuellner** [comment]
@fgregg, maybe tell me whether you prefer https://github.com/dmuellner/fastcluster/pull/31 in the new release or whether I should keep the current configuration.

**Comment by fgregg** [comment]
I think we don't need #31, looks like that might not be required?

**Comment by dmuellner** [comment]
It does not seem to be required. I just don't understand enough about manylinux to see which variant is preferable.

**Comment by dmuellner** [comment]
Never mind, the changes in https://github.com/dmuellner/fastcluster/pull/31 were indeed necessary, and I merged the pull request.

**Comment by dmuellner** [comment]
`pip install fastcluster` works with the new fastcluster release 1.2.5 on my computer with Python 3.10.
