### ISSUE TITLE
Interest in manylinux wheels

### ISSUE THREAD

**Issue by fgregg** [dmuellner/fastcluster#4]
Hi @dmuellner 

I helped set up wheel building for windows and mac os x about a year ago. In the meantime, the infrastructure for building [manylinux1](https://www.python.org/dev/peps/pep-0513/) wheels has gotten better. 

Is there interest in PRs for building manylinux1 wheels for fastcluster.

Here's an example of how I've been using Travis to build manylinux wheels: 

- https://github.com/datamade/doublemetaphone/blob/master/.travis.yml#L25-L48
- https://github.com/datamade/doublemetaphone/blob/master/.manylinux-install.sh
- https://pypi.python.org/pypi/DoubleMetaphone

**Comment by dmuellner** [comment]
Close this issue: done.
