### ISSUE TITLE
fastcluster is slower than Sklearn

### ISSUE THREAD

**Issue by dabasmoti** [dmuellner/fastcluster#53]
Hi,
I made comparison with fastcluster, sklearn and scipy(single linkage), 
All was +- the same (sklearn bit faster)
What should I need to check to get the boost?
I ran it on mac and ubuntu(ec2) with (100_000, 384) matrix.
Tnx

**Comment by dmuellner** [comment]
One possibility is that the three packages are indeed on par. Note that the fastcluster package is more than 10 years old. I have neither followed the other packages' evolution nor performed comparison tests in a long while. If all packages deliver similar performance, this is good news.
