### ISSUE TITLE
wrong error message

### ISSUE THREAD

**Issue by esadr** [dmuellner/fastcluster#6]
In the import of fastcluster, if I don't have the scipy.spatial.distance it will ask for scipy.partial.distance

the related part of code is:

try:
    from scipy.spatial.distance import pdist
except ImportError:
    def pdist(*args, **kwargs):
        raise ImportError('The fastcluster.linkage function cannot process '
                          'vector data since the function '
                          'scipy.partial.distance.pdist could not be  '
                          'imported.')

The exception seems wrong.

**Comment by dmuellner** [comment]
Thanks! Fixed on GitHub.
